server:
  port: 8680
  servlet:
    context-path: /ulises/usersserver

spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/usersserver
    username: postgres
    password: 630956076uL!

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

    hibernate:
      ddl-auto: update
